"""Add relationship at favourites

Revision ID: 8120711671ba
Revises: a4f7cfa09f8f
Create Date: 2024-02-05 23:25:32.041302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8120711671ba'
down_revision: Union[str, None] = 'a4f7cfa09f8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
