-
  name: booking_deploy
  hosts: localhost
  user: root
  tasks:
    - name: get k8s
      ansible.builtin.service:
        name: snap.microk8s.daemon-cluster-agent
        state: started
        enabled: true
    - name: deploy booking at k8s
      command: 'microk8s kubectl apply -f ~/workspaces/booking/k8s.yml'
